### ISSUE TITLE
Support creating statements like 'SELECT COUNT(DISTINCT UserId) FROM USERS'

### ISSUE THREAD

**Issue by kobynet** [dazinator/SQLGeneration#8]
Currently DISTINCT qualifier can only be added to the whole select statement and not inside COUNT etc.

**Comment by dazinator** [comment]
Hi @kobynet - thanks for raising this issue.

It may be better to raise this as an issue over on jehugaleahsa/SQLGeneration - as this repo is a fork from there, with some features I added for my own needs. Fixes made in this repo are unlikely to ever be merged back to the original (jehugaleahsa/SQLGeneration) where as fixes made in the original repo - I will happily merge into this fork if need be. 
If I do get any time I will try and pick this up over on jehugaleahsa/SQLGeneration

**Comment by kobynet** [comment]
Hi @dazinator 

Thanks for the reply, i'll open an issue in the origianl repo, the reason i opened here is because this was more active than the original repo.
